{
 "title": "Log de impressões do Windows em banco de dados MySQL",
 "tags": [
  "Impressão",
  "print",
  "Windows",
  "Log"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpi" }
   ]
  },
  {
   "title": "Grafico de Impressões",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    user AS usuario,\r\n    SUM(totalpages) AS value\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY user\r\nORDER BY value DESC\r\nLIMIT 15;\r\n"
    }
   ]
  },
  {
   "title": "Total de Páginas impressas ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_impresso\r\nFROM printlog;\r\n"
    }
   ]
  },
  {
   "title": "Total de impressões no mês anterior",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_mes_passado\r\nFROM printlog\r\nWHERE timecreated >= DATE_FORMAT(CURDATE() - INTERVAL 1 MONTH, '%Y-%m-01')\r\n  AND timecreated < DATE_FORMAT(CURDATE(), '%Y-%m-01');\r\n"
    }
   ]
  },
  {
   "title": "Total de impressões no Mês Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_paginas_mes\r\nFROM printlog\r\nWHERE \r\n    YEAR(timecreated) = YEAR(CURRENT_DATE())\r\n    AND MONTH(timecreated) = MONTH(CURRENT_DATE());\r\n"
    }
   ]
  },
  {
   "title": "Total de impressões nos Últimos 7 dias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT SUM(totalpages) AS total_7dias\r\nFROM printlog\r\nWHERE timecreated >= NOW() - INTERVAL 7 DAY;\r\n"
    }
   ]
  },
  {
   "title": "Total de páginas impressas Ontem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT SUM(totalpages) AS total_ontem\r\nFROM printlog\r\nWHERE timecreated >= CURDATE() - INTERVAL 1 DAY\r\n  AND timecreated < CURDATE();\r\n"
    }
   ]
  },
  {
   "title": "Total de páginas impressas Hoje",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT SUM(totalpages) AS total_hoje\r\nFROM printlog\r\nWHERE timecreated >= CURDATE()\r\n  AND timecreated < CURDATE() + INTERVAL 1 DAY;\r\n"
    }
   ]
  },
  {
   "title": "Impressões por Dia",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "dataset": "glpi",
     "rawSql": "SELECT \r\n    DATE(timecreated) AS time,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY DATE(timecreated)\r\nORDER BY time ASC;\r\n"
    }
   ]
  },
  { "title": "Comportamento de Impressão", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpi" }
   ]
  },
  {
   "title": "Quantidade de impressões por mês",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT\r\n    -- chave técnica para ordenar corretamente\r\n    DATE_FORMAT(timecreated, '%Y-%m')        AS ano_mes,\r\n    -- rótulo legível para o eixo / legenda\r\n    DATE_FORMAT(timecreated, '%M %Y')       AS mes,\r\n    SUM(totalpages)                         AS total_paginas\r\nFROM printlog\r\nWHERE timecreated >= DATE_SUB(CURDATE(), INTERVAL 12 MONTH)\r\nGROUP BY ano_mes, mes\r\nORDER BY ano_mes;\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de impressões dos últimos 30 dias",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 5, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    DATE(timecreated) AS dia,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated >= CURDATE() - INTERVAL 30 DAY\r\nGROUP BY DATE(timecreated)\r\nORDER BY dia ASC;\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de impressões dos últimos 7 dias",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 5, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    DATE(timecreated) AS dia,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated >= CURDATE() - INTERVAL 7 DAY\r\nGROUP BY DATE(timecreated)\r\nORDER BY dia ASC;\r\n"
    }
   ]
  },
  {
   "title": "Número de impressões de cada impressora",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY printer\r\nORDER BY total_paginas DESC\r\nLIMIT 30;\r\n"
    }
   ]
  },
  { "title": "Visão de Consumo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpi" }
   ]
  },
  {
   "title": "Número de impressões por usuário",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    user AS usuario,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY user\r\nORDER BY total_paginas DESC;\r\n"
    }
   ]
  },
  {
   "title": "Número de impressões por impressora",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 6, "y": 38 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY printer\r\nORDER BY total_paginas DESC;\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 - Por impressora",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 13, "y": 38 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT\r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY printer\r\nORDER BY total_paginas DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 - Uso por usuário",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    user AS usuario,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE timecreated BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY user\r\nORDER BY total_paginas DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  { "title": "Logs de Impressão", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "glpi" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    jobid AS trabalho,\r\n    DATE_FORMAT(timecreated, '%d/%m/%Y') AS data,\r\n    DATE_FORMAT(timecreated, '%H:%i:%s') AS hora,\r\n    client AS estacao,\r\n    user AS usuario,\r\n    printer AS impressora,\r\n    filename AS arquivo,\r\n    jobbytes AS tamanho,\r\n    pagecount AS paginas,\r\n    totalpages AS total\r\nFROM printlog\r\nORDER BY timecreated DESC\r\nLIMIT 500;\r\n"
    }
   ]
  }
 ]
}