{
 "title": "Log de impressões do Windows em banco de dados MySQL",
 "description": "Log de impressões do Windows em banco de dados MySQL",
 "tags": [
  "Impressão",
  "print",
  "Windows",
  "Log"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Grafico de Impressões Mensais",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT\r\n    user AS usuario,\r\n    SUM(totalpages) AS value\r\nFROM printlog\r\nWHERE MONTH(timecreated) = MONTH(NOW())\r\n  AND YEAR(timecreated) = YEAR(NOW())\r\nGROUP BY user\r\nORDER BY value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Numero de impressões por usuario",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    user AS usuario,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE DATE(timecreated) = CURRENT_DATE()\r\nGROUP BY user\r\nORDER BY total_paginas DESC;\r\n"
    }
   ]
  },
  {
   "title": "Numero de impressões por impressoras",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE DATE(timecreated) = CURRENT_DATE()\r\nGROUP BY printer\r\nORDER BY total_paginas DESC;\r\n"
    }
   ]
  },
  {
   "title": "Total de Páginas impressas ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_impresso\r\nFROM printlog;\r\n"
    }
   ]
  },
  {
   "title": "Total de impressões no Mês",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_paginas_mes\r\nFROM printlog\r\nWHERE \r\n    YEAR(timecreated) = YEAR(CURRENT_DATE())\r\n    AND MONTH(timecreated) = MONTH(CURRENT_DATE());\r\n"
    }
   ]
  },
  {
   "title": "Total de páginas impressas Ontem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_ontem\r\nFROM printlog\r\nWHERE DATE(timecreated) = DATE(NOW() - INTERVAL 1 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Total de páginas impressas Hoje",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    SUM(totalpages) AS total_hoje\r\nFROM printlog\r\nWHERE DATE(timecreated) = CURRENT_DATE();\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 - Uso Hoje",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT\r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE DATE(timecreated) = CURRENT_DATE()\r\nGROUP BY printer\r\nORDER BY total_paginas DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 - Uso por Login mensal",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 7, "y": 12 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    user AS usuario,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE \r\n    YEAR(timecreated) = YEAR(CURRENT_DATE())\r\n    AND MONTH(timecreated) = MONTH(CURRENT_DATE())\r\nGROUP BY user\r\nORDER BY total_paginas DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "TOP 10 - Uso Impressoras mensal",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "glpi",
     "rawSql": "SELECT\r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nWHERE MONTH(timecreated) = MONTH(CURDATE())\r\n  AND YEAR(timecreated) = YEAR(CURDATE())\r\nGROUP BY printer\r\nORDER BY total_paginas DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de impressões por mês",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT\r\n    -- chave técnica para ordenar corretamente\r\n    DATE_FORMAT(timecreated, '%Y-%m')        AS ano_mes,\r\n    -- rótulo legível para o eixo / legenda\r\n    DATE_FORMAT(timecreated, '%M %Y')       AS mes,\r\n    SUM(totalpages)                         AS total_paginas\r\nFROM printlog\r\nWHERE timecreated >= DATE_SUB(CURDATE(), INTERVAL 12 MONTH)\r\nGROUP BY ano_mes, mes\r\nORDER BY ano_mes;\r\n"
    }
   ]
  },
  {
   "title": "Quantidade de impressões por dia",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    DATE(timecreated) AS dia,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nGROUP BY DATE(timecreated)\r\nORDER BY dia ASC;\r\n"
    }
   ]
  },
  {
   "title": "Número de impressões de cada impressora",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    printer AS impressora,\r\n    SUM(totalpages) AS total_paginas\r\nFROM printlog\r\nGROUP BY printer\r\nORDER BY total_paginas DESC;\r\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "printlog",
     "rawSql": "SELECT \r\n    jobid AS trabalho,\r\n    DATE_FORMAT(timecreated, '%d/%m/%Y') AS data,\r\n    DATE_FORMAT(timecreated, '%H:%i:%s') AS hora,\r\n    client AS estacao,\r\n    user AS usuario,\r\n    printer AS impressora,\r\n    filename AS arquivo,\r\n    jobbytes AS tamanho,\r\n    pagecount AS paginas,\r\n    totalpages AS total\r\nFROM printlog\r\nORDER BY timecreated DESC\r\nLIMIT 500;\r\n"
    }
   ]
  }
 ]
}